package rebue.ord.mo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Database Table Remarks:
 *   订单任务
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ORD_TASK
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-21 11:37:33
 */
@ApiModel(value = "OrdTaskMo", description = "订单任务")
@JsonInclude(Include.NON_NULL)
public class OrdTaskMo implements Serializable {
    /**
     * Database Column Remarks:
     *   任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_TASK.ID
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @ApiModelProperty(value = "任务ID")
    private Long id;

    /**
     * Database Column Remarks:
     *   执行状态(-1:取消；0:未执行；1:已执行)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_TASK.EXECUTE_STATE
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @ApiModelProperty(value = "执行状态(-1:取消；0:未执行；1:已执行)")
    private Byte executeState;

    /**
     * Database Column Remarks:
     *   计划执行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_TASK.EXECUTE_PLAN_TIME
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @ApiModelProperty(value = "计划执行时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date executePlanTime;

    /**
     * Database Column Remarks:
     *   实际执行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_TASK.EXECUTE_FACT_TIME
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @ApiModelProperty(value = "实际执行时间")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date executeFactTime;

    /**
     * Database Column Remarks:
     *   任务类型（1：取消订单  2：订单签收）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_TASK.TASK_TYPE
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @ApiModelProperty(value = "任务类型（1：取消订单  2：订单签收）")
    private Byte taskType;

    /**
     * Database Column Remarks:
     *   订单ID(销售订单ID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORD_TASK.ORDER_ID
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @ApiModelProperty(value = "订单ID(销售订单ID)")
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_TASK.ID
     *
     * @return the value of ORD_TASK.ID
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_TASK.ID
     *
     * @param id the value for ORD_TASK.ID
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_TASK.EXECUTE_STATE
     *
     * @return the value of ORD_TASK.EXECUTE_STATE
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public Byte getExecuteState() {
        return executeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_TASK.EXECUTE_STATE
     *
     * @param executeState the value for ORD_TASK.EXECUTE_STATE
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public void setExecuteState(Byte executeState) {
        this.executeState = executeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_TASK.EXECUTE_PLAN_TIME
     *
     * @return the value of ORD_TASK.EXECUTE_PLAN_TIME
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public Date getExecutePlanTime() {
        return executePlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_TASK.EXECUTE_PLAN_TIME
     *
     * @param executePlanTime the value for ORD_TASK.EXECUTE_PLAN_TIME
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public void setExecutePlanTime(Date executePlanTime) {
        this.executePlanTime = executePlanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_TASK.EXECUTE_FACT_TIME
     *
     * @return the value of ORD_TASK.EXECUTE_FACT_TIME
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public Date getExecuteFactTime() {
        return executeFactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_TASK.EXECUTE_FACT_TIME
     *
     * @param executeFactTime the value for ORD_TASK.EXECUTE_FACT_TIME
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public void setExecuteFactTime(Date executeFactTime) {
        this.executeFactTime = executeFactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_TASK.TASK_TYPE
     *
     * @return the value of ORD_TASK.TASK_TYPE
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public Byte getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_TASK.TASK_TYPE
     *
     * @param taskType the value for ORD_TASK.TASK_TYPE
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public void setTaskType(Byte taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORD_TASK.ORDER_ID
     *
     * @return the value of ORD_TASK.ORDER_ID
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORD_TASK.ORDER_ID
     *
     * @param orderId the value for ORD_TASK.ORDER_ID
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", executeState=").append(executeState);
        sb.append(", executePlanTime=").append(executePlanTime);
        sb.append(", executeFactTime=").append(executeFactTime);
        sb.append(", taskType=").append(taskType);
        sb.append(", orderId=").append(orderId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrdTaskMo other = (OrdTaskMo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
        ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        return result;
    }
}