package rebue.ord.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.ord.mo.OrdAddrMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OrdAddrMapper extends MybatisBaseMapper<OrdAddrMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    int insert(OrdAddrMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    int insertSelective(OrdAddrMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    OrdAddrMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    int updateByPrimaryKeySelective(OrdAddrMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    int updateByPrimaryKey(OrdAddrMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    List<OrdAddrMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    List<OrdAddrMo> selectSelective(OrdAddrMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ADDR
     *
     * @mbg.generated 2018-06-06 11:12:41
     */
    boolean existSelective(OrdAddrMo record);
}