package rebue.ord.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.ord.mo.OrdOrderDetailMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OrdOrderDetailMapper extends MybatisBaseMapper<OrdOrderDetailMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    int insert(OrdOrderDetailMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    int insertSelective(OrdOrderDetailMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    OrdOrderDetailMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    int updateByPrimaryKeySelective(OrdOrderDetailMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    int updateByPrimaryKey(OrdOrderDetailMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    List<OrdOrderDetailMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    List<OrdOrderDetailMo> selectSelective(OrdOrderDetailMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_ORDER_DETAIL
     *
     * @mbg.generated 2018-05-05 16:21:19
     */
    boolean existSelective(OrdOrderDetailMo record);
}