package rebue.ord.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.ord.mo.OrdOrderMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import java.util.Map;

@Mapper
public interface OrdOrderMapper extends MybatisBaseMapper<OrdOrderMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	int insert(OrdOrderMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	int insertSelective(OrdOrderMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	OrdOrderMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	int updateByPrimaryKeySelective(OrdOrderMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	int updateByPrimaryKey(OrdOrderMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	List<OrdOrderMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	List<OrdOrderMo> selectSelective(OrdOrderMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_ORDER
	 *
	 * @mbg.generated 2018-04-24 10:45:44
	 */
	boolean existSelective(OrdOrderMo record);

	/**
	 * 查询用户订单信息 Title: selectOrderInfo Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月9日 下午4:47:12
	 */
	List<OrdOrderMo> selectOrderInfo(Map<String, Object> map);

	/**
	 * 用户取消订单修改订单状态 Title: cancellationOrderUpdateOrderState Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月9日 下午7:27:48
	 */
	int cancellationOrderUpdateOrderState(OrdOrderMo record);

	/**
	 * 修改订单实际金额 Title: updateOrderRealMoney Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月12日 下午2:38:57
	 */
	int updateOrderRealMoney(OrdOrderMo record);

	/**
	 * 设置快递公司 Title: setUpExpressCompany Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月13日 上午11:19:14
	 */
	int setUpExpressCompany(OrdOrderMo record);

	/**
	 * 取消发货修改订单状态 Title: cancelDeliveryUpdateOrderState Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月13日 下午2:56:33
	 */
	int cancelDeliveryUpdateOrderState(OrdOrderMo record);

	/**
	 * 确认发货并修改订单状态 Title: shipmentConfirmation Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月13日 下午6:15:29
	 */
	int shipmentConfirmation(OrdOrderMo record);

	/**
	 * 订单签收 Title: orderSignIn Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月14日 下午2:18:26
	 */
	int orderSignIn(OrdOrderMo record);
}