package rebue.ord.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.ord.mo.OrdReturnMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import rebue.ord.ro.OrdReturnRo;

@Mapper
public interface OrdReturnMapper extends MybatisBaseMapper<OrdReturnMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	int insert(OrdReturnMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	int insertSelective(OrdReturnMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	OrdReturnMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	int updateByPrimaryKeySelective(OrdReturnMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	int updateByPrimaryKey(OrdReturnMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	List<OrdReturnMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	List<OrdReturnMo> selectSelective(OrdReturnMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_RETURN
	 *
	 * @mbg.generated 2018-04-27 11:48:43
	 */
	boolean existSelective(OrdReturnMo record);

	/**
	 * 查询分页列表信息 Title: selectReturnPageList Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月21日 下午3:35:27
	 */
	List<OrdReturnRo> selectReturnPageList(OrdReturnMo record);

	/**
	 * 退货审核通过 Title: updateReturnApprove Description:
	 * 
	 * @param record
	 * @return
	 * @date 2018年4月21日 下午5:14:48
	 */
	int updateReturnApprove(OrdReturnMo record);
}