package rebue.ord.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.ord.mo.OrdTaskMo;
import rebue.robotech.mapper.MybatisBaseMapper;

@Mapper
public interface OrdTaskMapper extends MybatisBaseMapper<OrdTaskMo, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    int insert(OrdTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    int insertSelective(OrdTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    OrdTaskMo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    int updateByPrimaryKeySelective(OrdTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    int updateByPrimaryKey(OrdTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    List<OrdTaskMo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    List<OrdTaskMo> selectSelective(OrdTaskMo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    boolean existByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORD_TASK
     *
     * @mbg.generated 2018-05-21 11:37:33
     */
    boolean existSelective(OrdTaskMo record);
}