package rebue.ord.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import rebue.ord.mo.OrdTaskMo;
import rebue.robotech.mapper.MybatisBaseMapper;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface OrdTaskMapper extends MybatisBaseMapper<OrdTaskMo, Long> {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	int insert(OrdTaskMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	int insertSelective(OrdTaskMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	OrdTaskMo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	int updateByPrimaryKeySelective(OrdTaskMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	int updateByPrimaryKey(OrdTaskMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	List<OrdTaskMo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	List<OrdTaskMo> selectSelective(OrdTaskMo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	boolean existByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ORD_TASK
	 *
	 * @mbg.generated 2018-06-06 11:12:41
	 */
	boolean existSelective(OrdTaskMo record);

	/**
	 * 查询订单任务数量 Title: selectByExecutePlanTimeBeforeNow Description:
	 * 
	 * @param executeState
	 * @param taskType
	 * @return
	 * @date 2018年5月28日 上午10:40:02
	 */
	@Select("select ID from ORD_TASK where EXECUTE_STATE=${executeState} and TASK_TYPE=${taskType} and EXECUTE_PLAN_TIME <= SYSDATE()")
	List<Long> selectByExecutePlanTimeBeforeNow(
			@Param("executeState") byte executeState,
			@Param("taskType") byte taskType);

	/**
	 * 执行订单签收任务 Title: executeSignInOrderTask Description:
	 * 
	 * @return
	 * @date 2018年5月21日 下午2:11:18
	 */
	@Update("update ORD_TASK set EXECUTE_STATE=#{doneState}, EXECUTE_FACT_TIME=#{executeFactTime,jdbcType=TIMESTAMP} where ID=#{id} and EXECUTE_STATE=#{noneState}")
	int executeSignInOrderTask(@Param("executeFactTime") Date executeFactTime,
			@Param("id") long id, @Param("doneState") Byte doneState,
			@Param("noneState") Byte noneState);
}