-- 一个订单详情不能有超过1个上家订单详情
SELECT 
    DOWNLINE_ORDER_DETAIL_ID, COUNT(ID)
FROM
    ORD_BUY_RELATION
GROUP BY DOWNLINE_ORDER_DETAIL_ID
HAVING COUNT(ID) > 1;

-- 一个订单详情不能有超过2个下家订单详情
SELECT 
    UPLINE_ORDER_DETAIL_ID, COUNT(ID)
FROM
    ORD_BUY_RELATION
GROUP BY UPLINE_ORDER_DETAIL_ID
HAVING COUNT(ID) > 2;